using System.Collections.Generic;
using Jotunn.Managers;

namespace Bygd.Framework
{
    internal static class Localizations
    {
        public static void Register()
        {
            var loc = LocalizationManager.Instance.GetLocalization();
            loc.AddTranslation("Russian", Russian());
            loc.AddTranslation("English", English());
        }

        private static Dictionary<string, string> Russian() => new Dictionary<string, string>
        {
            // Shared UI
            { "ui_build_house", "Построить дом" },
            { "ui_talk", "Поговорить" },
            { "ui_cancel", "Отмена" },
            { "ui_open", "Открыть" },
            { "ui_npc_present", "На месте" },
            { "ui_npc_absent", "Пусто" },
            { "blueprint_select_title", "Выбери план" },
            { "blueprint_entry_label", "{0} ({1} дет., ур.{2}+)" },
            { "blueprint_selected_hint", "План '{0}'. [E] Повернуть, [Shift+E] Построить" },
            { "anchor_return_first", "Сначала верни аванпост игроку!" },
            // Outpost
            { "piece_outpost_table", "Стол Старосты" },
            { "piece_outpost_table_desc", "Основа аванпоста. Построй дом вокруг — и придёт староста." },
            { "msg_outpost_founded", "Аванпост основан!" },
            { "msg_outpost_placement", "Стол Старосты: попытка установки" },
            { "msg_outpost_no_roof", "Стол Старосты: нет крыши" },
            { "msg_outpost_needs_roof", "Стол Старосты должен стоять под крышей!" },
            { "msg_settler_arrived", "Поселенец прибыл в аванпост!" },
            { "msg_settler_left", "Поселенец покинул аванпост — нет огня или кровати!" },
            { "outpost_status_player", "Принадлежит игроку" },
            { "outpost_status_npc", "Передан NPC" },
            { "outpost_transfer_to_npc", "Передать NPC" },
            { "outpost_transfer_to_player", "Вернуть игроку" },
            { "outpost_transferred", "Аванпост передан NPC" },
            { "outpost_returned", "Аванпост возвращён игроку" },
            { "outpost_needs_chest", "Поставь сундук снаружи для подношений!" },
            { "outpost_chest_linked", "Сундук подношений привязан к аванпосту" },
            { "outpost_resources_collected", "Ресурсы приняты! Дрова: {0}, Калории: {1}, Смола: {2}" },
            { "outpost_needs_wood", "Нам нужны дрова!" },
            { "outpost_needs_food", "Нужна еда!" },
            { "outpost_level_up", "Аванпост улучшен! Уровень: {0}" },
            { "outpost_all_good", "Запасы в порядке." },
            { "outpost_relation_up", "Отношения улучшились!" },
            { "outpost_access_granted", "Староста разрешил вам входить в дом!" },
            { "outpost_abandoned", "Аванпост заброшен — староста ушёл..." },
            { "outpost_degraded", "Аванпост деградирует — нужны ресурсы!" },
            { "outpost_starving", "Мы голодаем! Нет ни дров, ни еды!" },
            { "outpost_low_supplies", "Припасы на исходе. Скоро кончатся." },
            { "outpost_needs_table", "Стол бы обеденный поставить... Не на чём трапезничать." },
            { "settler_name", "Староста" },
            { "settler_talk", "Поговорить" },
            { "settler_idle", "Порядок в аванпосте важнее суеты." },
            // Courier
            { "piece_courier_post", "Почтовый Столб" },
            { "piece_courier_post_desc", "Рабочее место курьера. Построй дом рядом с аванпостом — и придёт курьер." },
            { "courier_name", "Курьер" },
            { "courier_talk", "Поговорить" },
            { "msg_courier_arrived", "Курьер прибыл в аванпост!" },
            { "msg_courier_left", "Курьер покинул аванпост!" },
            { "courier_post_placed", "Почтовый столб установлен!" },
            { "courier_post_needs_roof", "Почтовый столб должен стоять под крышей!" },
            { "courier_post_needs_outpost", "Нужен переданный аванпост уровня 2+ рядом!" },
            { "courier_post_occupied", "Курьер на месте" },
            { "courier_post_empty", "Пусто" },
            { "courier_idle", "Жду указаний." },
            { "courier_no_supplies", "Без припасов далеко не уедешь..." },
            { "courier_low_supplies", "Припасы на исходе, дорога будет тяжёлой." },
            { "courier_ready", "Готов к выезду! Только скажи куда." },
            { "courier_returned", "Курьер вернулся!" },
            { "courier_post_patrolling", "Курьер патрулирует" },
            { "courier_post_resting", "Курьер отдыхает" },
            { "courier_patrol_status", "Курьер в пути: {0}/{1} остановок" },
            { "courier_patrol_done", "Курьер завершил патруль" },
            { "courier_patrol_home", "домой" },
            { "courier_patrol_stop", "остановка {0}/{1}" },
            { "courier_patrol_hover", "Патруль: {0}, {1}%{2}" },
            { "courier_patrol_bag_info", ", в сумке: {0}" },
            // Mail post
            { "piece_mailpost", "Почтовый Пункт" },
            { "piece_mailpost_desc", "Остановка курьера. Поставь сундук и табличку с @адресом рядом." },
            { "mailpost_placed", "Почтовый пункт установлен!" },
            { "mailpost_has_mail", "Есть посылка" },
            { "mailpost_empty", "Пусто" },
            { "mailpost_needs_chest", "Поставь сундук рядом!" },
            { "mailpost_needs_sign", "Поставь табличку с @адресом рядом!" },
            { "mailpost_sign_empty", "Напиши @адрес на табличке!" },
            { "mailpost_chest_empty", "Сундук пуст. Положи посылку для @{0}." },
            { "mailpost_ready", "Готово к отправке: {0} предметов → @{1}" },
            { "mailpost_sent", "Курьер вызван! {0} предметов → @{1}" },
            { "mailpost_no_courier", "Нет доступного курьера!" },
            { "mailpost_courier_busy", "Курьер уже в пути!" },
            { "mailpost_send_failed", "Не удалось отправить (нет бюджета?)" },
            // Lumberjack
            { "piece_lumberjack_post", "Столб Дровосека" },
            { "piece_lumberjack_post_desc", "Рабочее место дровосека. Построй дом рядом с аванпостом — и придёт дровосек." },
            { "lumberjack_name", "Дровосек" },
            { "lumberjack_talk", "Поговорить" },
            { "lumberjack_post_placed", "Столб дровосека установлен!" },
            { "lumberjack_idle", "Лес сам себя не срубит... хотя нет, срубит." },
            { "lumberjack_working", "Не мешай, тут работают!" },
            { "lumberjack_present", "Дровосек на месте" },
            { "lumberjack_missing", "Нет дровосека" },
            { "lumberjack_task_idle", "Отдыхает" },
            { "lumberjack_task_no_trees", "Нет деревьев рядом" },
            { "lumberjack_task_walking", "Идёт к дереву" },
            { "lumberjack_task_chopping", "Рубит дерево" },
            { "lumberjack_task_collecting", "Собирает дрова" },
            { "lumberjack_task_planting", "Сажает саженец" },
            { "lumberjack_task_returning", "Возвращается" },
        };

        private static Dictionary<string, string> English() => new Dictionary<string, string>
        {
            // Shared UI
            { "ui_build_house", "Build house" },
            { "ui_talk", "Talk" },
            { "ui_cancel", "Cancel" },
            { "ui_open", "Open" },
            { "ui_npc_present", "Present" },
            { "ui_npc_absent", "Empty" },
            { "blueprint_select_title", "Choose blueprint" },
            { "blueprint_entry_label", "{0} ({1} pcs, lvl {2}+)" },
            { "blueprint_selected_hint", "Blueprint '{0}'. [E] Rotate, [Shift+E] Build" },
            { "anchor_return_first", "Return the outpost to the player first!" },
            // Outpost
            { "piece_outpost_table", "Elder's Table" },
            { "piece_outpost_table_desc", "Outpost foundation. Build a house around it — and an elder will come." },
            { "msg_outpost_founded", "Outpost founded!" },
            { "msg_outpost_placement", "Elder's Table: placement attempt" },
            { "msg_outpost_no_roof", "Elder's Table: no roof" },
            { "msg_outpost_needs_roof", "Elder's Table must be placed under a roof!" },
            { "msg_settler_arrived", "A settler has arrived at the outpost!" },
            { "msg_settler_left", "The settler left the outpost — no fire or bed!" },
            { "outpost_status_player", "Owned by player" },
            { "outpost_status_npc", "Transferred to NPC" },
            { "outpost_transfer_to_npc", "Transfer to NPC" },
            { "outpost_transfer_to_player", "Return to player" },
            { "outpost_transferred", "Outpost transferred to NPC" },
            { "outpost_returned", "Outpost returned to player" },
            { "outpost_needs_chest", "Place a chest outside for offerings!" },
            { "outpost_chest_linked", "Offering chest linked to outpost" },
            { "outpost_resources_collected", "Resources accepted! Wood: {0}, Calories: {1}, Resin: {2}" },
            { "outpost_needs_wood", "We need firewood!" },
            { "outpost_needs_food", "We need food!" },
            { "outpost_level_up", "Outpost upgraded! Level: {0}" },
            { "outpost_all_good", "Supplies are in order." },
            { "outpost_relation_up", "Relations improved!" },
            { "outpost_access_granted", "The elder has granted you access to the house!" },
            { "outpost_abandoned", "Outpost abandoned — the elder has left..." },
            { "outpost_degraded", "Outpost is degrading — resources needed!" },
            { "outpost_starving", "We are starving! No wood or food!" },
            { "outpost_low_supplies", "Supplies are running low. They will run out soon." },
            { "outpost_needs_table", "We could use a dining table... Nowhere to eat properly." },
            { "settler_name", "Elder" },
            { "settler_talk", "Talk" },
            { "settler_idle", "Order in the outpost matters more than haste." },
            // Courier
            { "piece_courier_post", "Courier Post" },
            { "piece_courier_post_desc", "Courier's workplace. Build a house near an outpost — and a courier will come." },
            { "courier_name", "Courier" },
            { "courier_talk", "Talk" },
            { "msg_courier_arrived", "A courier has arrived at the outpost!" },
            { "msg_courier_left", "The courier has left the outpost!" },
            { "courier_post_placed", "Courier post placed!" },
            { "courier_post_needs_roof", "Courier post must be placed under a roof!" },
            { "courier_post_needs_outpost", "Need a transferred level 2+ outpost nearby!" },
            { "courier_post_occupied", "Courier present" },
            { "courier_post_empty", "Empty" },
            { "courier_idle", "Awaiting orders." },
            { "courier_no_supplies", "Can't travel without supplies..." },
            { "courier_low_supplies", "Supplies are running low, it'll be a tough road." },
            { "courier_ready", "Ready to ride! Just say where." },
            { "courier_returned", "Courier has returned!" },
            { "courier_post_patrolling", "Courier on patrol" },
            { "courier_post_resting", "Courier resting" },
            { "courier_patrol_status", "Courier on patrol: {0}/{1} stops" },
            { "courier_patrol_done", "Courier finished patrol" },
            { "courier_patrol_home", "home" },
            { "courier_patrol_stop", "stop {0}/{1}" },
            { "courier_patrol_hover", "Patrol: {0}, {1}%{2}" },
            { "courier_patrol_bag_info", ", bag: {0}" },
            // Mail post
            { "piece_mailpost", "Mail Post" },
            { "piece_mailpost_desc", "Courier stop. Place a chest and a sign with @address nearby." },
            { "mailpost_placed", "Mail post placed!" },
            { "mailpost_has_mail", "Mail pending" },
            { "mailpost_empty", "Empty" },
            { "mailpost_needs_chest", "Place a chest nearby!" },
            { "mailpost_needs_sign", "Place a sign with @address nearby!" },
            { "mailpost_sign_empty", "Write @address on the sign!" },
            { "mailpost_chest_empty", "Chest is empty. Place a parcel for @{0}." },
            { "mailpost_ready", "Ready to send: {0} items → @{1}" },
            { "mailpost_sent", "Courier called! {0} items → @{1}" },
            { "mailpost_no_courier", "No courier available!" },
            { "mailpost_courier_busy", "Courier is already en route!" },
            { "mailpost_send_failed", "Failed to send (no budget?)" },
            // Lumberjack
            { "piece_lumberjack_post", "Lumberjack Post" },
            { "piece_lumberjack_post_desc", "Lumberjack's workplace. Build a house near an outpost — and a lumberjack will come." },
            { "lumberjack_name", "Lumberjack" },
            { "lumberjack_talk", "Talk" },
            { "lumberjack_post_placed", "Lumberjack post placed!" },
            { "lumberjack_idle", "The forest won't chop itself... well, actually it will." },
            { "lumberjack_working", "Don't disturb, working here!" },
            { "lumberjack_present", "Lumberjack present" },
            { "lumberjack_missing", "No lumberjack" },
            { "lumberjack_task_idle", "Idle" },
            { "lumberjack_task_no_trees", "No trees nearby" },
            { "lumberjack_task_walking", "Walking to tree" },
            { "lumberjack_task_chopping", "Chopping tree" },
            { "lumberjack_task_collecting", "Collecting wood" },
            { "lumberjack_task_planting", "Planting sapling" },
            { "lumberjack_task_returning", "Returning" },
        };
    }
}
